### ISSUE TITLE
Details on how to build with a different version

### ISSUE THREAD

**Issue by Hypercubed** [webnexusmobile/cy-m1#1]
Thank you for this... the Dockerfile as is worked for getting a 9.3.1 version.  Any hints on what it takes to build with a different version?  I tried simply change the version numbers in the Dockerfile but that didn't work.

**Comment by zettpunkt79** [comment]
Hi, what version did you try do build? It might be this Dockerfile won't work for some older cypress versions with dependencies which are not available for ARM64.
