### ISSUE TITLE
how to add chrome?

### ISSUE THREAD

**Issue by miukki** [webnexusmobile/cy-m1#2]
how to add chrome?

is it ok jsut add like this: 
```
FROM --platform=linux/arm64 node:16.13.0-bullseye as builder
FROM --platform=linux/arm64 cypress/browsers:node16.14.2-slim-chrome100-ff99-edge

```

**Comment by zettpunkt79** [comment]
Progress on support for other browsers than electron can be tracked here https://github.com/cypress-io/cypress-docker-images/issues/695
