### ISSUE TITLE
Cannot find module 'cypress'

### ISSUE THREAD

**Issue by rnunezil** [webnexusmobile/cy-m1#3]
I get this following error after building your image and then running it.   I thought Cypress is supposed to run within the image.

Details:  Error: Cannot find module 'cypress'
Require stack:
- /e2e/cypress.config.js
- /root/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/lib/plugins/child/run_require_async_child.js
- /root/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/lib/plugins/child/require_async_child.js

**Comment by zettpunkt79** [comment]
This repo has not been adapted to cypress versions of > 10.x 
Please note that cypress 10.2, which you were trying to build, supports M1 natively, see cypress blog.

**Comment by rnunezil** [comment]
I read that but that is to run Cypress outside Docker.   I am trying to run Cypress inside Docker using the (https://github.com/cypress-io/cypress-docker-images/tree/master/included) 10.2.0 latest image but running it errors out under my M1 chip.   I was hoping your image file would be a workaround.
